import { InterviewType } from '@/constants/enums/interview-type';
import { SkillLevel } from '@/constants/enums/skill-level';

export const dummy = {
  candidates: [
    {
      id: 1,
      fullName: 'John Smith',
      interviewType: InterviewType.ADVANCED,
      dateTaken: '2025-03-15',
      hardSkills: SkillLevel.ADVANCED,
      softSkills: SkillLevel.EXPERT,
      technicalSkills: SkillLevel.ADVANCED,
      overallLevel: SkillLevel.ADVANCED,
      overallFeedback:
        'Strong technical background with excellent communication skills. Shows great potential for leadership roles.',
    },
    {
      id: 2,
      fullName: 'Sarah Johnson',
      interviewType: InterviewType.BASIC,
      dateTaken: '2025-03-14',
      hardSkills: SkillLevel.PROFICIENT,
      softSkills: SkillLevel.EXPERT,
      technicalSkills: SkillLevel.PROFICIENT,
      overallLevel: SkillLevel.PROFICIENT,
      overallFeedback:
        'Outstanding interpersonal skills. Technical knowledge needs some improvement but shows quick learning ability.',
    },
    {
      id: 3,
      fullName: 'Michael Chen',
      interviewType: InterviewType.TECHNICAL,
      dateTaken: '2025-03-13',
      hardSkills: SkillLevel.EXPERT,
      softSkills: SkillLevel.PROFICIENT,
      technicalSkills: SkillLevel.EXPERT,
      overallLevel: SkillLevel.EXPERT,
      overallFeedback:
        'Exceptional technical expertise. Could benefit from more practice in presentation skills.',
    },
    {
      id: 4,
      fullName: 'Emily Davis',
      interviewType: InterviewType.BASIC,
      dateTaken: '2025-03-12',
      hardSkills: SkillLevel.PROFICIENT,
      softSkills: SkillLevel.ADVANCED,
      technicalSkills: SkillLevel.PROFICIENT,
      overallLevel: SkillLevel.PROFICIENT,
      overallFeedback: 'Well-rounded candidate with good balance of technical and soft skills.',
    },
    {
      id: 5,
      fullName: 'David Wilson',
      interviewType: InterviewType.ADVANCED,
      dateTaken: '2025-03-11',
      hardSkills: SkillLevel.ADVANCED,
      softSkills: SkillLevel.ADVANCED,
      technicalSkills: SkillLevel.EXPERT,
      overallLevel: SkillLevel.ADVANCED,
      overallFeedback: 'Impressive problem-solving abilities and strong team collaboration skills.',
    },
    {
      id: 6,
      fullName: 'Lisa Anderson',
      interviewType: InterviewType.TECHNICAL,
      dateTaken: '2025-03-10',
      hardSkills: SkillLevel.EXPERT,
      softSkills: SkillLevel.PROFICIENT,
      technicalSkills: SkillLevel.EXPERT,
      overallLevel: SkillLevel.EXPERT,
      overallFeedback:
        'Outstanding technical knowledge, particularly in system architecture. Communication could be improved.',
    },
    {
      id: 7,
      fullName: 'James Taylor',
      interviewType: InterviewType.BASIC,
      dateTaken: '2025-03-09',
      hardSkills: SkillLevel.PROFICIENT,
      softSkills: SkillLevel.ADVANCED,
      technicalSkills: SkillLevel.PROFICIENT,
      overallLevel: SkillLevel.PROFICIENT,
      overallFeedback:
        'Natural leader with strong soft skills. Technical skills are developing well.',
    },
    {
      id: 8,
      fullName: 'Maria Garcia',
      interviewType: InterviewType.ADVANCED,
      dateTaken: '2025-03-08',
      hardSkills: SkillLevel.ADVANCED,
      softSkills: SkillLevel.ADVANCED,
      technicalSkills: SkillLevel.ADVANCED,
      overallLevel: SkillLevel.ADVANCED,
      overallFeedback: 'Excellent project management skills with strong technical foundation.',
    },
    {
      id: 9,
      fullName: 'Robert Martinez',
      interviewType: InterviewType.TECHNICAL,
      dateTaken: '2025-03-07',
      hardSkills: SkillLevel.EXPERT,
      softSkills: SkillLevel.PROFICIENT,
      technicalSkills: SkillLevel.EXPERT,
      overallLevel: SkillLevel.EXPERT,
      overallFeedback: 'Deep technical expertise in cloud architecture. Good team player.',
    },
    {
      id: 10,
      fullName: 'Emma Thompson',
      interviewType: InterviewType.BASIC,
      dateTaken: '2025-03-06',
      hardSkills: SkillLevel.PROFICIENT,
      softSkills: SkillLevel.EXPERT,
      technicalSkills: SkillLevel.PROFICIENT,
      overallLevel: SkillLevel.PROFICIENT,
      overallFeedback: 'Strong communication and leadership potential. Solid technical foundation.',
    },
    {
      id: 11,
      fullName: 'Daniel Lee',
      interviewType: InterviewType.ADVANCED,
      dateTaken: '2025-03-05',
      hardSkills: SkillLevel.ADVANCED,
      softSkills: SkillLevel.ADVANCED,
      technicalSkills: SkillLevel.EXPERT,
      overallLevel: SkillLevel.ADVANCED,
      overallFeedback: 'Innovative problem solver with excellent analytical skills.',
    },
    {
      id: 12,
      fullName: 'Sophie Brown',
      interviewType: InterviewType.BEHAVIORAL,
      dateTaken: '2025-03-04',
      hardSkills: SkillLevel.EXPERT,
      softSkills: SkillLevel.PROFICIENT,
      technicalSkills: SkillLevel.EXPERT,
      overallLevel: SkillLevel.EXPERT,
      overallFeedback:
        'Expert in backend development. Shows good potential for technical leadership.',
    },
  ],
};
